#!/usr/bin/env python
 
import sys
import getconfig 
import pspherewrapper 
def main():
    if sys.version_info < (3, 0):
        reload(sys)
        sys.setdefaultencoding('utf-8')
    cfg = getconfig.Config()
    args = cfg.parseargs()
    print args
    out = args.get('ovfroot ')
    sys.exit(pspherewrapper.init(cfg, args))

main()
                     
